# Generated by Django 4.0.3 on 2022-07-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensity', models.CharField(max_length=100)),
                ('focus', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=100)),
                ('concern', models.CharField(max_length=100)),
                ('complaints', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=40)),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=40)),
                ('add', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=100)),
                ('specifydisease', models.CharField(max_length=100)),
                ('plan', models.CharField(max_length=100)),
                ('total', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=100)),
                ('gymbags', models.CharField(max_length=100)),
                ('mat', models.CharField(max_length=100)),
                ('others', models.CharField(max_length=100)),
                ('Loss', models.CharField(max_length=100)),
                ('locker', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DietPlan', models.CharField(max_length=100)),
                ('Trainer', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=100)),
            ],
        ),
    ]
