# Generated by Django 3.1.6 on 2022-07-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exerciseplan',
            name='Duration',
        ),
        migrations.RemoveField(
            model_name='exerciseplan',
            name='customer_plan',
        ),
        migrations.AlterField(
            model_name='exerciseplan',
            name='planID',
            field=models.BigAutoField(default='', primary_key=True, serialize=False),
        ),
    ]
