# Generated by Django 3.1.6 on 2022-07-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0002_auto_20220706_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplan',
            name='planID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
