# Generated by Django 3.1.6 on 2022-07-07 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0004_auto_20220706_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='clothing',
            new_name='gymbags',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='extras',
            new_name='locker',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='focus',
            new_name='loss',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='supplements',
            new_name='mat',
        ),
        migrations.AddField(
            model_name='products',
            name='others',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='products',
            name='protein',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='productID',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
