# Generated by Django 3.1.6 on 2022-07-07 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0005_auto_20220707_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='loss',
            new_name='Loss',
        ),
    ]
