# Generated by Django 3.1.6 on 2022-07-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ftsys', '0006_auto_20220707_0801'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Feedback',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='review',
        ),
    ]
